import f1 from "../img/products/f1.jpg";
import f2 from "../img/products/f2.jpg";
import f3 from "../img/products/f3.jpg";
import f4 from "../img/products/f4.jpg";
import f5 from "../img/products/f5.jpg";
import f6 from "../img/products/f6.jpg";
import f7 from "../img/products/f7.jpg";
import f8 from "../img/products/f8.jpg";
import n1 from "../img/products/n1.jpg";
import n2 from "../img/products/n2.jpg";
import n3 from "../img/products/n3.jpg";
import n4 from "../img/products/n4.jpg";
import n5 from "../img/products/n5.jpg";
import n6 from "../img/products/n6.jpg";
import n7 from "../img/products/n7.jpg";
import n8 from "../img/products/n8.jpg";
import k1 from "../img/products/k1.png";
import k2 from "../img/products/k2.png";
import k3 from "../img/products/k3.png";
import k4 from "../img/products/k4.png";
import k5 from "../img/products/k5.png";
import k6 from "../img/products/k6.png";
import k7 from "../img/products/k7.png";
import k8 from "../img/products/k8.png";
import l1 from "../img/products/l1.png";
import l2 from "../img/products/l2.png";
import l3 from "../img/products/l3.png";
import l4 from "../img/products/l4.png";
import l5 from "../img/products/l5.png";
import l6 from "../img/products/l6.png";
import l7 from "../img/products/l7.png";
import l8 from "../img/products/l8.png";

export const imgSet1 = [f1, f2, f3, f4, f5, f6, f7, f8];
export const imgSet2 = [n1, n2, n3, n4, n5, n6, n7, n8];
export const imgSet3 = [k1, k2, k3, k4, k5, k6, k7, k8];
export const imgSet4 = [l1, l2, l3, l4, l5, l6, l7, l8];
